# Generated by Django 4.2.3 on 2023-07-21 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('publish_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='مکان نشر')),
                ('publish_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال نشر')),
                ('date_of_publish', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ فهرست نویسی')),
                ('language', models.CharField(blank=True, choices=[('فارسی', 'فارسی'), ('انگلیسی', 'انگلیسی')], max_length=255, null=True, verbose_name='زبان')),
                ('ISBN', models.CharField(blank=True, max_length=255, null=True, verbose_name='شابک')),
                ('classification', models.CharField(blank=True, choices=[('دیویی', 'دیویی'), ('کنگره', 'کنگره')], max_length=255, null=True, verbose_name='رده بندی')),
                ('registration_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره ثبت')),
                ('version', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره ثبت')),
                ('summery', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('number_of_pages', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد صفحات کتاب')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookInvolvedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('role', models.CharField(choices=[('نویسنده', 'نویسنده'), ('سرشناسه', 'سرشناسه'), ('مترجم', 'مترجم'), ('پدید آورنده', 'پدید آورنده'), ('گوینده', 'گوینده'), ('سایر', 'سایر')], max_length=255, verbose_name='نقش')),
                ('images', models.ManyToManyField(blank=True, to='file_gallery.filegallery', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'دست اندر کار کتاب',
                'verbose_name_plural': 'دست اندر کاران کتاب',
            },
        ),
        migrations.CreateModel(
            name='MagicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug_title', models.CharField(editable=False, max_length=255, verbose_name='اسلاگ عنوان')),
                ('word_type', models.CharField(choices=[('category', 'category'), ('keyword', 'keyword'), ('subject', 'subject')], max_length=255, verbose_name='نوع کلمه')),
            ],
            options={
                'verbose_name': 'کلمه جادویی',
                'verbose_name_plural': 'کلمات جادویی',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=255, verbose_name='نام انتشارات')),
                ('publisher_address', models.CharField(max_length=255, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'انتشارات',
                'verbose_name_plural': 'انتشارات',
            },
        ),
        migrations.CreateModel(
            name='BookWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wished_books', models.ManyToManyField(to='bookshelf.book', verbose_name='کتابهای مورد علاقه')),
            ],
            options={
                'verbose_name': 'کتاب های مورد علاقه کاربران',
                'verbose_name_plural': 'کتاب های مورد علاقه کاربران',
            },
        ),
        migrations.CreateModel(
            name='BookReadingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_read_last_page', models.PositiveIntegerField(default=1, verbose_name='اخرین صفحه مطالعه شده')),
                ('book_completion_percentage', models.PositiveIntegerField(default=0, verbose_name='درصد مطالعه شده')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتابهای مورد علاقه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درصد مطالعه کتاب ها',
                'verbose_name_plural': 'درصد مطالعه کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_demo', models.FileField(blank=True, null=True, upload_to='pdf_demo', verbose_name='فایل دموی نوشتاری انلاین')),
                ('pdf_source', models.FileField(blank=True, null=True, upload_to='pdf_source', verbose_name='فایل نوشتاری کامل انلاین')),
                ('review', tinymce.models.HTMLField(blank=True, null=True, verbose_name='نقد و بررسی')),
                ('visited_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='دفعات مشاهده')),
                ('is_physical_available', models.BooleanField(default=False, verbose_name='آیا کتاب به صورتی فیزیکی موجود است؟')),
                ('is_published_on_site', models.BooleanField(default=False, verbose_name='آیا کتاب در سایت ارائه شود؟')),
                ('is_featured', models.BooleanField(default=False, verbose_name='آیا کتاب ویژه است؟')),
                ('audio_demo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_demo', to='file_gallery.filegallery', verbose_name='فایل دموی صوتی')),
                ('audio_source', models.ManyToManyField(blank=True, related_name='audio_source', to='file_gallery.filegallery', verbose_name='فایل های کامل صوتی')),
                ('audio_speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_involved_person_audio_speaker', to='bookshelf.bookinvolvedperson', verbose_name='نام گوینده صوتی')),
                ('book', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب')),
                ('visited_by_users', models.ManyToManyField(blank=True, related_name='visited_by_users', to=settings.AUTH_USER_MODEL, verbose_name='کاربر های مشاهده کننده')),
            ],
            options={
                'verbose_name': 'پروفایل کتاب',
                'verbose_name_plural': 'پروفایل کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='BookAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assignment', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ واگذاری')),
                ('date_of_return', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بازگرداندن')),
                ('is_this_book_returned', models.BooleanField(default=False, editable=False, verbose_name='آیا این کتاب بازگردانده شده است؟')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='قرض گیرنده')),
            ],
            options={
                'verbose_name': 'واگذاری',
                'verbose_name_plural': 'واگذاری',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='book_involved_person_authors', to='bookshelf.bookinvolvedperson', verbose_name='سرشناسگان'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_images',
            field=models.ManyToManyField(blank=True, related_name='book_images', to='file_gallery.filegallery', verbose_name='سایر تصاویر مرتبط به کتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='magic_word_categories', to='bookshelf.magicword', verbose_name='دسته ها'),
        ),
        migrations.AddField(
            model_name='book',
            name='interpreters',
            field=models.ManyToManyField(blank=True, related_name='book_involved_person_interpreters', to='bookshelf.bookinvolvedperson', verbose_name='پدیدآورندگان'),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='magic_word_keywords', to='bookshelf.magicword', verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='book',
            name='on_paper_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_paper_image', to='file_gallery.filegallery', verbose_name='تصویر جلد کتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.publisher', verbose_name='ناشر'),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='magic_word_subjects', to='bookshelf.magicword', verbose_name='موضوعات'),
        ),
    ]
