# Generated by Django 4.2.3 on 2023-07-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_remove_bookprofile_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreadingcompletion',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreadingcompletion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookwishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookwishlist',
            name='wished_books',
        ),
        migrations.DeleteModel(
            name='BookAssign',
        ),
        migrations.DeleteModel(
            name='BookReadingCompletion',
        ),
        migrations.DeleteModel(
            name='BookWishlist',
        ),
    ]
