# Generated by Django 4.2.3 on 2023-07-21 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveSmallIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('image', models.ImageField(upload_to='main page slider', verbose_name='بنر صفحه اصلی')),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنر صفحه اصلی',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='BooOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب هفته')),
            ],
            options={
                'verbose_name': 'کتاب هفته',
                'verbose_name_plural': 'کتاب هفته',
            },
        ),
    ]
