# Generated by Django 4.2.3 on 2023-07-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_remove_bookprofile_is_featured'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boooftheweek',
            options={'verbose_name': 'کتاب هفته', 'verbose_name_plural': 'کتاب های هفته'},
        ),
        migrations.AlterField(
            model_name='boooftheweek',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب'),
        ),
        migrations.CreateModel(
            name='FeaturedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'کتاب ویژه',
                'verbose_name_plural': 'کتاب های ویژه',
            },
        ),
    ]
