# Generated by Django 4.2.3 on 2023-07-21 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', django_jalali.db.models.jDateField(verbose_name='تاریخ مجاز مراجعه و دریافت کتاب')),
                ('from_hour', models.CharField(max_length=255, verbose_name='از ساعت')),
                ('to_hour', models.CharField(max_length=255, verbose_name='تا ساعت')),
            ],
            options={
                'verbose_name': 'تاریخ و ساعت قابل مراجعه',
                'verbose_name_plural': 'تاریخ و ساعت قابل مراجعه',
            },
        ),
        migrations.CreateModel(
            name='RequestLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', django_jalali.db.models.jDateField(verbose_name='تاریخ مورد نظر جهت مراجعه و دریافت کتاب')),
                ('date_of_placed_request', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('hour', models.CharField(max_length=255, verbose_name='ساعت مراجعه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_request_processed', models.BooleanField(default=False, verbose_name='آیا این درخواست رسیدگی شده است؟')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب مورد درخواست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست کننده')),
            ],
            options={
                'verbose_name': 'درخواست کتاب',
                'verbose_name_plural': 'در خواست های کتاب',
                'ordering': ['date_of_placed_request'],
            },
        ),
    ]
