# Generated by Django 4.2.3 on 2023-07-21 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page', models.PositiveIntegerField(default=0, verbose_name='آخرین صفحه مطالعه شده')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب درحال مطالعه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کتاب در حال مطالعه',
                'verbose_name_plural': 'کتاب های در حال مطالعه',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='اطلاعیه')),
                ('time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.message', verbose_name='اطلاعیه')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
                'ordering': ['-notification__time'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.message', verbose_name='پیام شخصی')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربران دریافت کننده پیام')),
            ],
            options={
                'verbose_name': 'پیام شخصی',
                'verbose_name_plural': 'پیام های شخصی',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_profile_pic', verbose_name='عکس پروفایل')),
                ('is_notification_seen', models.BooleanField(default=False, verbose_name='آیا نوتیفیکیشن ها خوانده شد؟')),
                ('is_message_seen', models.BooleanField(default=False, verbose_name='آیا پیام ها خوانده شد؟')),
                ('message_box', models.ManyToManyField(blank=True, to='accounts.privatemessage', verbose_name='پیام ها')),
                ('notification_box', models.ManyToManyField(blank=True, to='accounts.notification', verbose_name='اطلاعیه ها')),
                ('reading_book', models.ManyToManyField(blank=True, related_name='reading_book', to='accounts.bookreadinghistory', verbose_name='کتاب های درحال مطالعه')),
                ('specific_book_only_for_this_user', models.ManyToManyField(related_name='specific_book_only_for_this_user', to='bookshelf.book', verbose_name='کتاب های خاص این کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wish_list', models.ManyToManyField(blank=True, related_name='wish_list', to='bookshelf.book', verbose_name='کتاب های اضافه شده به علاقه مندی ها')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
