# Generated by Django 4.2.3 on 2023-07-21 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0002_remove_bookprofile_is_featured'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page', models.PositiveIntegerField(default=0, editable=False, verbose_name='آخرین صفحه مطالعه شده')),
                ('is_finished', models.BooleanField(default=False, editable=False, verbose_name='خواندن کتاب پایان یافته است؟')),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب درحال مطالعه')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش مطالعه کاربر',
                'verbose_name_plural': 'گزارش مطالعه کاربران',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reading_book',
        ),
        migrations.DeleteModel(
            name='BookReadingHistory',
        ),
    ]
