# Generated by Django 4.2.3 on 2023-07-22 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_remove_bookreadingcompletion_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_userreadingreport_remove_userprofile_reading_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assignment', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ واگذاری')),
                ('date_of_return', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بازگرداندن')),
                ('is_this_book_returned', models.BooleanField(default=False, editable=False, verbose_name='آیا این کتاب بازگردانده شده است؟')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='قرض گیرنده')),
            ],
            options={
                'verbose_name': 'واگذاری',
                'verbose_name_plural': 'واگذاری',
            },
        ),
        migrations.CreateModel(
            name='UserBookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reading', models.BooleanField(default=False, editable=False, verbose_name='آیا کتاب در حال مطالعه است؟')),
                ('last_page', models.PositiveIntegerField(default=0, editable=False, verbose_name='آخرین صفحه مطالعه شده')),
                ('is_finished', models.BooleanField(default=False, editable=False, verbose_name='آیا خواندن کتاب پایان یافته است؟')),
                ('is_Wished', models.BooleanField(default=False, editable=False, verbose_name='آیا کتاب در لیست مطالعه ی آتی است؟')),
                ('is_liked', models.BooleanField(default=False, editable=False, verbose_name='آیا کتاب جزو موارد مورد علاقه است؟')),
                ('book', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت کتاب کاربر',
                'verbose_name_plural': 'وضعیت کتاب های کاربران',
            },
        ),
        migrations.DeleteModel(
            name='UserReadingReport',
        ),
    ]
