# Generated by Django 4.2.3 on 2023-07-22 11:00

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbookassign_userbookstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookstatus',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 7, 22, 11, 0, 34, 937814), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='userbookstatus',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 7, 22, 11, 0, 34, 937814), verbose_name='تاریخ بروزرسانی'),
        ),
    ]
