# Generated by Django 4.2.3 on 2023-07-22 11:00

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userbookstatus_created_at_userbookstatus_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookstatus',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userbookstatus',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
