# Generated by Django 4.2.3 on 2023-07-22 11:05

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userbookstatus_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userbookstatus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userbookstatus',
            name='finish_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ پایان مطالعه کتاب'),
        ),
        migrations.AddField(
            model_name='userbookstatus',
            name='like_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ اضافه شدن به لیست علاقه مندی ها'),
        ),
        migrations.AddField(
            model_name='userbookstatus',
            name='wish_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ اضافه شدن به لیست مطالعه اتی'),
        ),
    ]
