# Generated by Django 4.2.3 on 2023-07-21 23:25

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_alt', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_src', models.FileField(upload_to='files', verbose_name='سورس فایل')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'گالری فایل',
                'verbose_name_plural': 'گالری فایل ها',
            },
        ),
    ]
